//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\balaz\AppData\Local\Temp\fijmhpzj.5bv\MetaGeneratorParser.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace MetaDslx.Compiler {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IMetaGeneratorParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class MetaGeneratorParserBaseListener : IMetaGeneratorParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] MetaGeneratorParser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] MetaGeneratorParser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDeclaration([NotNull] MetaGeneratorParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDeclaration([NotNull] MetaGeneratorParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.generatorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGeneratorDeclaration([NotNull] MetaGeneratorParser.GeneratorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.generatorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGeneratorDeclaration([NotNull] MetaGeneratorParser.GeneratorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.usingNamespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingNamespaceDeclaration([NotNull] MetaGeneratorParser.UsingNamespaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.usingNamespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingNamespaceDeclaration([NotNull] MetaGeneratorParser.UsingNamespaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.usingGeneratorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUsingGeneratorDeclaration([NotNull] MetaGeneratorParser.UsingGeneratorDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.usingGeneratorDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUsingGeneratorDeclaration([NotNull] MetaGeneratorParser.UsingGeneratorDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.configDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfigDeclaration([NotNull] MetaGeneratorParser.ConfigDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.configDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfigDeclaration([NotNull] MetaGeneratorParser.ConfigDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.configPropertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfigPropertyDeclaration([NotNull] MetaGeneratorParser.ConfigPropertyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.configPropertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfigPropertyDeclaration([NotNull] MetaGeneratorParser.ConfigPropertyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.configPropertyGroupDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConfigPropertyGroupDeclaration([NotNull] MetaGeneratorParser.ConfigPropertyGroupDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.configPropertyGroupDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConfigPropertyGroupDeclaration([NotNull] MetaGeneratorParser.ConfigPropertyGroupDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMethodDeclaration([NotNull] MetaGeneratorParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.methodDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMethodDeclaration([NotNull] MetaGeneratorParser.MethodDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionDeclaration([NotNull] MetaGeneratorParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.functionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionDeclaration([NotNull] MetaGeneratorParser.FunctionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.functionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionSignature([NotNull] MetaGeneratorParser.FunctionSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.functionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionSignature([NotNull] MetaGeneratorParser.FunctionSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] MetaGeneratorParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] MetaGeneratorParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] MetaGeneratorParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] MetaGeneratorParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBody([NotNull] MetaGeneratorParser.BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBody([NotNull] MetaGeneratorParser.BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] MetaGeneratorParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] MetaGeneratorParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.variableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableDeclarationStatement([NotNull] MetaGeneratorParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.variableDeclarationStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableDeclarationStatement([NotNull] MetaGeneratorParser.VariableDeclarationStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] MetaGeneratorParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] MetaGeneratorParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionStatement([NotNull] MetaGeneratorParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.expressionStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionStatement([NotNull] MetaGeneratorParser.ExpressionStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] MetaGeneratorParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] MetaGeneratorParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.ifStatementBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatementBegin([NotNull] MetaGeneratorParser.IfStatementBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.ifStatementBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatementBegin([NotNull] MetaGeneratorParser.IfStatementBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.elseIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseIfStatement([NotNull] MetaGeneratorParser.ElseIfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.elseIfStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseIfStatement([NotNull] MetaGeneratorParser.ElseIfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.ifStatementElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatementElse([NotNull] MetaGeneratorParser.IfStatementElseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.ifStatementElse"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatementElse([NotNull] MetaGeneratorParser.IfStatementElseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.ifStatementEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatementEnd([NotNull] MetaGeneratorParser.IfStatementEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.ifStatementEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatementEnd([NotNull] MetaGeneratorParser.IfStatementEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStatement([NotNull] MetaGeneratorParser.LoopStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStatement([NotNull] MetaGeneratorParser.LoopStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopStatementBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStatementBegin([NotNull] MetaGeneratorParser.LoopStatementBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopStatementBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStatementBegin([NotNull] MetaGeneratorParser.LoopStatementBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopStatementEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopStatementEnd([NotNull] MetaGeneratorParser.LoopStatementEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopStatementEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopStatementEnd([NotNull] MetaGeneratorParser.LoopStatementEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopChain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopChain([NotNull] MetaGeneratorParser.LoopChainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopChain"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopChain([NotNull] MetaGeneratorParser.LoopChainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopChainItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopChainItem([NotNull] MetaGeneratorParser.LoopChainItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopChainItem"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopChainItem([NotNull] MetaGeneratorParser.LoopChainItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopChainMemberAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopChainMemberAccessExpression([NotNull] MetaGeneratorParser.LoopChainMemberAccessExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopChainMemberAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopChainMemberAccessExpression([NotNull] MetaGeneratorParser.LoopChainMemberAccessExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopChainMethodCallExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopChainMethodCallExpression([NotNull] MetaGeneratorParser.LoopChainMethodCallExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopChainMethodCallExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopChainMethodCallExpression([NotNull] MetaGeneratorParser.LoopChainMethodCallExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopChainIdentifierExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopChainIdentifierExpression([NotNull] MetaGeneratorParser.LoopChainIdentifierExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopChainIdentifierExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopChainIdentifierExpression([NotNull] MetaGeneratorParser.LoopChainIdentifierExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopChainTypeofExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopChainTypeofExpression([NotNull] MetaGeneratorParser.LoopChainTypeofExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopChainTypeofExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopChainTypeofExpression([NotNull] MetaGeneratorParser.LoopChainTypeofExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopWhereExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopWhereExpression([NotNull] MetaGeneratorParser.LoopWhereExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopWhereExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopWhereExpression([NotNull] MetaGeneratorParser.LoopWhereExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopRunExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopRunExpression([NotNull] MetaGeneratorParser.LoopRunExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopRunExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopRunExpression([NotNull] MetaGeneratorParser.LoopRunExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopRunList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopRunList([NotNull] MetaGeneratorParser.LoopRunListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopRunList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopRunList([NotNull] MetaGeneratorParser.LoopRunListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.loopRun"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopRun([NotNull] MetaGeneratorParser.LoopRunContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.loopRun"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopRun([NotNull] MetaGeneratorParser.LoopRunContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatement([NotNull] MetaGeneratorParser.SwitchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatement([NotNull] MetaGeneratorParser.SwitchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchStatementBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatementBegin([NotNull] MetaGeneratorParser.SwitchStatementBeginContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchStatementBegin"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatementBegin([NotNull] MetaGeneratorParser.SwitchStatementBeginContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchStatementEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchStatementEnd([NotNull] MetaGeneratorParser.SwitchStatementEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchStatementEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchStatementEnd([NotNull] MetaGeneratorParser.SwitchStatementEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchBranchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBranchStatement([NotNull] MetaGeneratorParser.SwitchBranchStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchBranchStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBranchStatement([NotNull] MetaGeneratorParser.SwitchBranchStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchBranchHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchBranchHeadStatement([NotNull] MetaGeneratorParser.SwitchBranchHeadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchBranchHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchBranchHeadStatement([NotNull] MetaGeneratorParser.SwitchBranchHeadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchCaseOrTypeIsHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchCaseOrTypeIsHeadStatement([NotNull] MetaGeneratorParser.SwitchCaseOrTypeIsHeadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchCaseOrTypeIsHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchCaseOrTypeIsHeadStatement([NotNull] MetaGeneratorParser.SwitchCaseOrTypeIsHeadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchCaseHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchCaseHeadStatement([NotNull] MetaGeneratorParser.SwitchCaseHeadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchCaseHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchCaseHeadStatement([NotNull] MetaGeneratorParser.SwitchCaseHeadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchTypeIsHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchTypeIsHeadStatement([NotNull] MetaGeneratorParser.SwitchTypeIsHeadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchTypeIsHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchTypeIsHeadStatement([NotNull] MetaGeneratorParser.SwitchTypeIsHeadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchTypeAsHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchTypeAsHeadStatement([NotNull] MetaGeneratorParser.SwitchTypeAsHeadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchTypeAsHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchTypeAsHeadStatement([NotNull] MetaGeneratorParser.SwitchTypeAsHeadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchDefaultStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchDefaultStatement([NotNull] MetaGeneratorParser.SwitchDefaultStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchDefaultStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchDefaultStatement([NotNull] MetaGeneratorParser.SwitchDefaultStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.switchDefaultHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchDefaultHeadStatement([NotNull] MetaGeneratorParser.SwitchDefaultHeadStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.switchDefaultHeadStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchDefaultHeadStatement([NotNull] MetaGeneratorParser.SwitchDefaultHeadStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateDeclaration([NotNull] MetaGeneratorParser.TemplateDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateDeclaration([NotNull] MetaGeneratorParser.TemplateDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateSignature([NotNull] MetaGeneratorParser.TemplateSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateSignature([NotNull] MetaGeneratorParser.TemplateSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateBody([NotNull] MetaGeneratorParser.TemplateBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateBody([NotNull] MetaGeneratorParser.TemplateBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateContentLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateContentLine([NotNull] MetaGeneratorParser.TemplateContentLineContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateContentLine"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateContentLine([NotNull] MetaGeneratorParser.TemplateContentLineContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateOutput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateOutput([NotNull] MetaGeneratorParser.TemplateOutputContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateOutput"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateOutput([NotNull] MetaGeneratorParser.TemplateOutputContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateLineEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateLineEnd([NotNull] MetaGeneratorParser.TemplateLineEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateLineEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateLineEnd([NotNull] MetaGeneratorParser.TemplateLineEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateStatementStartEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateStatementStartEnd([NotNull] MetaGeneratorParser.TemplateStatementStartEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateStatementStartEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateStatementStartEnd([NotNull] MetaGeneratorParser.TemplateStatementStartEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.templateStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTemplateStatement([NotNull] MetaGeneratorParser.TemplateStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.templateStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTemplateStatement([NotNull] MetaGeneratorParser.TemplateStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typeArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeArgumentList([NotNull] MetaGeneratorParser.TypeArgumentListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typeArgumentList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeArgumentList([NotNull] MetaGeneratorParser.TypeArgumentListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.predefinedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredefinedType([NotNull] MetaGeneratorParser.PredefinedTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.predefinedType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredefinedType([NotNull] MetaGeneratorParser.PredefinedTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typeReferenceList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeReferenceList([NotNull] MetaGeneratorParser.TypeReferenceListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typeReferenceList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeReferenceList([NotNull] MetaGeneratorParser.TypeReferenceListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeReference([NotNull] MetaGeneratorParser.TypeReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeReference([NotNull] MetaGeneratorParser.TypeReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] MetaGeneratorParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] MetaGeneratorParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.nullableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullableType([NotNull] MetaGeneratorParser.NullableTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.nullableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullableType([NotNull] MetaGeneratorParser.NullableTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericType([NotNull] MetaGeneratorParser.GenericTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.genericType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericType([NotNull] MetaGeneratorParser.GenericTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleType([NotNull] MetaGeneratorParser.SimpleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleType([NotNull] MetaGeneratorParser.SimpleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.voidType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoidType([NotNull] MetaGeneratorParser.VoidTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.voidType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoidType([NotNull] MetaGeneratorParser.VoidTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnType([NotNull] MetaGeneratorParser.ReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnType([NotNull] MetaGeneratorParser.ReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionList([NotNull] MetaGeneratorParser.ExpressionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.expressionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionList([NotNull] MetaGeneratorParser.ExpressionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableReference([NotNull] MetaGeneratorParser.VariableReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.variableReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableReference([NotNull] MetaGeneratorParser.VariableReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.rankSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRankSpecifiers([NotNull] MetaGeneratorParser.RankSpecifiersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.rankSpecifiers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRankSpecifiers([NotNull] MetaGeneratorParser.RankSpecifiersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.rankSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRankSpecifier([NotNull] MetaGeneratorParser.RankSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.rankSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRankSpecifier([NotNull] MetaGeneratorParser.RankSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.unboundTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnboundTypeName([NotNull] MetaGeneratorParser.UnboundTypeNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.unboundTypeName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnboundTypeName([NotNull] MetaGeneratorParser.UnboundTypeNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.genericDimensionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenericDimensionSpecifier([NotNull] MetaGeneratorParser.GenericDimensionSpecifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.genericDimensionSpecifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenericDimensionSpecifier([NotNull] MetaGeneratorParser.GenericDimensionSpecifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.explicitAnonymousFunctionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitAnonymousFunctionSignature([NotNull] MetaGeneratorParser.ExplicitAnonymousFunctionSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.explicitAnonymousFunctionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitAnonymousFunctionSignature([NotNull] MetaGeneratorParser.ExplicitAnonymousFunctionSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.implicitAnonymousFunctionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicitAnonymousFunctionSignature([NotNull] MetaGeneratorParser.ImplicitAnonymousFunctionSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.implicitAnonymousFunctionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicitAnonymousFunctionSignature([NotNull] MetaGeneratorParser.ImplicitAnonymousFunctionSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.singleParamAnonymousFunctionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingleParamAnonymousFunctionSignature([NotNull] MetaGeneratorParser.SingleParamAnonymousFunctionSignatureContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.singleParamAnonymousFunctionSignature"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingleParamAnonymousFunctionSignature([NotNull] MetaGeneratorParser.SingleParamAnonymousFunctionSignatureContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.explicitParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitParameter([NotNull] MetaGeneratorParser.ExplicitParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.explicitParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitParameter([NotNull] MetaGeneratorParser.ExplicitParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.implicitParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterImplicitParameter([NotNull] MetaGeneratorParser.ImplicitParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.implicitParameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitImplicitParameter([NotNull] MetaGeneratorParser.ImplicitParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typeofUnboundTypeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeofUnboundTypeExpression([NotNull] MetaGeneratorParser.TypeofUnboundTypeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typeofUnboundTypeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeofUnboundTypeExpression([NotNull] MetaGeneratorParser.TypeofUnboundTypeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.additionExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditionExpression([NotNull] MetaGeneratorParser.AdditionExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.additionExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditionExpression([NotNull] MetaGeneratorParser.AdditionExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typecheckExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypecheckExpression([NotNull] MetaGeneratorParser.TypecheckExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typecheckExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypecheckExpression([NotNull] MetaGeneratorParser.TypecheckExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationalExpression([NotNull] MetaGeneratorParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.relationalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationalExpression([NotNull] MetaGeneratorParser.RelationalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.identifierExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierExpression([NotNull] MetaGeneratorParser.IdentifierExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.identifierExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierExpression([NotNull] MetaGeneratorParser.IdentifierExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.postExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPostExpression([NotNull] MetaGeneratorParser.PostExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.postExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPostExpression([NotNull] MetaGeneratorParser.PostExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typeofVoidExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeofVoidExpression([NotNull] MetaGeneratorParser.TypeofVoidExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typeofVoidExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeofVoidExpression([NotNull] MetaGeneratorParser.TypeofVoidExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.parenthesizedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthesizedExpression([NotNull] MetaGeneratorParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.parenthesizedExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthesizedExpression([NotNull] MetaGeneratorParser.ParenthesizedExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.bitwiseAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwiseAndExpression([NotNull] MetaGeneratorParser.BitwiseAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.bitwiseAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwiseAndExpression([NotNull] MetaGeneratorParser.BitwiseAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalAndExpression([NotNull] MetaGeneratorParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.logicalAndExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalAndExpression([NotNull] MetaGeneratorParser.LogicalAndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.functionCallExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionCallExpression([NotNull] MetaGeneratorParser.FunctionCallExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.functionCallExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionCallExpression([NotNull] MetaGeneratorParser.FunctionCallExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.memberAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMemberAccessExpression([NotNull] MetaGeneratorParser.MemberAccessExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.memberAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMemberAccessExpression([NotNull] MetaGeneratorParser.MemberAccessExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] MetaGeneratorParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] MetaGeneratorParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typecastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypecastExpression([NotNull] MetaGeneratorParser.TypecastExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typecastExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypecastExpression([NotNull] MetaGeneratorParser.TypecastExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.logicalXorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalXorExpression([NotNull] MetaGeneratorParser.LogicalXorExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.logicalXorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalXorExpression([NotNull] MetaGeneratorParser.LogicalXorExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.predefinedTypeMemberAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPredefinedTypeMemberAccessExpression([NotNull] MetaGeneratorParser.PredefinedTypeMemberAccessExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.predefinedTypeMemberAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPredefinedTypeMemberAccessExpression([NotNull] MetaGeneratorParser.PredefinedTypeMemberAccessExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.bitwiseXorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwiseXorExpression([NotNull] MetaGeneratorParser.BitwiseXorExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.bitwiseXorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwiseXorExpression([NotNull] MetaGeneratorParser.BitwiseXorExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLambdaExpression([NotNull] MetaGeneratorParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.lambdaExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLambdaExpression([NotNull] MetaGeneratorParser.LambdaExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.defaultValueExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDefaultValueExpression([NotNull] MetaGeneratorParser.DefaultValueExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.defaultValueExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDefaultValueExpression([NotNull] MetaGeneratorParser.DefaultValueExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionalExpression([NotNull] MetaGeneratorParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.conditionalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionalExpression([NotNull] MetaGeneratorParser.ConditionalExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignmentExpression([NotNull] MetaGeneratorParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.assignmentExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignmentExpression([NotNull] MetaGeneratorParser.AssignmentExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.multiplicationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiplicationExpression([NotNull] MetaGeneratorParser.MultiplicationExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.multiplicationExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiplicationExpression([NotNull] MetaGeneratorParser.MultiplicationExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.newObjectOrCollectionWithConstructorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNewObjectOrCollectionWithConstructorExpression([NotNull] MetaGeneratorParser.NewObjectOrCollectionWithConstructorExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.newObjectOrCollectionWithConstructorExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNewObjectOrCollectionWithConstructorExpression([NotNull] MetaGeneratorParser.NewObjectOrCollectionWithConstructorExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLogicalOrExpression([NotNull] MetaGeneratorParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.logicalOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLogicalOrExpression([NotNull] MetaGeneratorParser.LogicalOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.bitwiseOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBitwiseOrExpression([NotNull] MetaGeneratorParser.BitwiseOrExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.bitwiseOrExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBitwiseOrExpression([NotNull] MetaGeneratorParser.BitwiseOrExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.hasLoopExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHasLoopExpression([NotNull] MetaGeneratorParser.HasLoopExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.hasLoopExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHasLoopExpression([NotNull] MetaGeneratorParser.HasLoopExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.thisExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterThisExpression([NotNull] MetaGeneratorParser.ThisExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.thisExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitThisExpression([NotNull] MetaGeneratorParser.ThisExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.elementAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElementAccessExpression([NotNull] MetaGeneratorParser.ElementAccessExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.elementAccessExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElementAccessExpression([NotNull] MetaGeneratorParser.ElementAccessExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.typeofTypeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeofTypeExpression([NotNull] MetaGeneratorParser.TypeofTypeExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.typeofTypeExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeofTypeExpression([NotNull] MetaGeneratorParser.TypeofTypeExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualityExpression([NotNull] MetaGeneratorParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.equalityExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualityExpression([NotNull] MetaGeneratorParser.EqualityExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.literalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExpression([NotNull] MetaGeneratorParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.literalExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExpression([NotNull] MetaGeneratorParser.LiteralExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] MetaGeneratorParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] MetaGeneratorParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] MetaGeneratorParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] MetaGeneratorParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] MetaGeneratorParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] MetaGeneratorParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] MetaGeneratorParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] MetaGeneratorParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.nullLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullLiteral([NotNull] MetaGeneratorParser.NullLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.nullLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullLiteral([NotNull] MetaGeneratorParser.NullLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteral([NotNull] MetaGeneratorParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteral([NotNull] MetaGeneratorParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.numberLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberLiteral([NotNull] MetaGeneratorParser.NumberLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.numberLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberLiteral([NotNull] MetaGeneratorParser.NumberLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] MetaGeneratorParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] MetaGeneratorParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.decimalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalLiteral([NotNull] MetaGeneratorParser.DecimalLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.decimalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalLiteral([NotNull] MetaGeneratorParser.DecimalLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.scientificLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScientificLiteral([NotNull] MetaGeneratorParser.ScientificLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.scientificLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScientificLiteral([NotNull] MetaGeneratorParser.ScientificLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.dateOrTimeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDateOrTimeLiteral([NotNull] MetaGeneratorParser.DateOrTimeLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.dateOrTimeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDateOrTimeLiteral([NotNull] MetaGeneratorParser.DateOrTimeLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.dateTimeOffsetLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDateTimeOffsetLiteral([NotNull] MetaGeneratorParser.DateTimeOffsetLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.dateTimeOffsetLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDateTimeOffsetLiteral([NotNull] MetaGeneratorParser.DateTimeOffsetLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.dateTimeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDateTimeLiteral([NotNull] MetaGeneratorParser.DateTimeLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.dateTimeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDateTimeLiteral([NotNull] MetaGeneratorParser.DateTimeLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.dateLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDateLiteral([NotNull] MetaGeneratorParser.DateLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.dateLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDateLiteral([NotNull] MetaGeneratorParser.DateLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.timeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTimeLiteral([NotNull] MetaGeneratorParser.TimeLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.timeLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTimeLiteral([NotNull] MetaGeneratorParser.TimeLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.charLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharLiteral([NotNull] MetaGeneratorParser.CharLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.charLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharLiteral([NotNull] MetaGeneratorParser.CharLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] MetaGeneratorParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] MetaGeneratorParser.StringLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="MetaGeneratorParser.guidLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGuidLiteral([NotNull] MetaGeneratorParser.GuidLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="MetaGeneratorParser.guidLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGuidLiteral([NotNull] MetaGeneratorParser.GuidLiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace MetaDslx.Compiler
