<?xml version="1.0" encoding="utf-8"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:type="ecore:EPackage" xmi:id="4b66ba75-8aea-4399-8b40-8e09219c9211" name="railDsl" nsURI="http://www.bme.hu/iit/vke/raildsl" nsPrefix="railDsl" xmlns:xmi="http://www.omg.org/XMI">
  <eClassifiers xmi:type="ecore:EClass" xmi:id="f2295996-8bb1-4e53-9060-df351d7f770c" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Station">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="b688a30b-cbc1-4742-bca3-1c0ff6ff37a4" changeable="True" eContainingClass="f2295996-8bb1-4e53-9060-df351d7f770c" name="declarations" eType="a86ef574-0b0e-4af3-a321-bea96948a4f0" ordered="True" unique="True" upperBound="-1" containment="True" resolveProxies="True" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="a86ef574-0b0e-4af3-a321-bea96948a4f0" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Declaration" abstract="True" />
  <eClassifiers xmi:type="ecore:EClass" xmi:id="18de1e20-800d-4aa3-a36b-8eaed0cde3fe" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="TrackObject" abstract="True">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="6586cb06-f8d1-4c70-be5b-3d29b995cb87" changeable="True" eContainingClass="18de1e20-800d-4aa3-a36b-8eaed0cde3fe" name="length" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="effb8822-c6cd-4517-9790-5a111e4e66fb" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Vertex">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="69f8ccf0-9b69-4d88-ade7-6d9c2ac41b86" changeable="True" eContainingClass="effb8822-c6cd-4517-9790-5a111e4e66fb" name="kind" eType="4392d532-ee04-4e82-aa35-32c979b7ac46" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="ca401d50-d582-4f16-9b31-d4ad2080e92f" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Segment">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="073a7c06-19c1-4129-adec-807644ec5126" changeable="True" eContainingClass="ca401d50-d582-4f16-9b31-d4ad2080e92f" name="start" eType="effb8822-c6cd-4517-9790-5a111e4e66fb" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="85fe81cf-88f5-4b0d-b56a-ce6ad107eee9" changeable="True" eContainingClass="ca401d50-d582-4f16-9b31-d4ad2080e92f" name="end" eType="effb8822-c6cd-4517-9790-5a111e4e66fb" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="3d2d5268-865d-423e-b8a6-01064f1185ad" changeable="True" eContainingClass="ca401d50-d582-4f16-9b31-d4ad2080e92f" name="objects" eType="01d594c5-07e4-48bc-9a0b-04d1137826c2" ordered="True" unique="True" upperBound="-1" containment="True" resolveProxies="True" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="01d594c5-07e4-48bc-9a0b-04d1137826c2" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="SegmentObject" abstract="True">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="0f2c746c-9d81-40be-bbf5-3a334c3e05bc" changeable="True" eContainingClass="01d594c5-07e4-48bc-9a0b-04d1137826c2" name="position" eType="c457d96a-7789-4f20-a588-932696e1dd15" ordered="True" unique="True" upperBound="1" containment="True" resolveProxies="True" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="2004046b-946b-471a-912b-746470e52d64" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Derailer">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="ff5b06b0-b46d-4f8f-99e0-2b6583c5f3ef" changeable="True" eContainingClass="2004046b-946b-471a-912b-746470e52d64" name="active" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="67176795-f766-4621-8509-80c0bc4027ff" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="LevelCrossing">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="8a71edd1-bcca-4e2e-a87a-8fc116f2c432" changeable="True" eContainingClass="67176795-f766-4621-8509-80c0bc4027ff" name="closed" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="2e3c6432-9438-45e5-96da-1c8d62c2f51c" changeable="True" eContainingClass="67176795-f766-4621-8509-80c0bc4027ff" name="length" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="f9df8a4f-68f1-4b87-90b2-dc7461e51986" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Signal">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="3b5e0af2-2bf7-4934-b072-a22eb333d53b" changeable="True" eContainingClass="f9df8a4f-68f1-4b87-90b2-dc7461e51986" name="distantFor" eType="f9df8a4f-68f1-4b87-90b2-dc7461e51986" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="e5fc1e51-480b-47bd-9ca8-ee9a41cd5fba" changeable="True" eContainingClass="f9df8a4f-68f1-4b87-90b2-dc7461e51986" name="main" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="c954bbd3-209a-4607-b048-6188e9f1718a" changeable="True" eContainingClass="f9df8a4f-68f1-4b87-90b2-dc7461e51986" name="shunting" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="be88f021-070b-44bb-b1d9-25ed0500614e" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Platform">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="0bf98cc9-c8c3-4038-a24f-c5c99dc85339" changeable="True" eContainingClass="be88f021-070b-44bb-b1d9-25ed0500614e" name="length" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="c457d96a-7789-4f20-a588-932696e1dd15" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="SegmentPosition">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="4abe3f5d-8b64-481d-add5-022796c9fa64" changeable="True" eContainingClass="c457d96a-7789-4f20-a588-932696e1dd15" name="atStart" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="b9a78453-1389-44f4-a144-63fc081a3fa2" changeable="True" eContainingClass="c457d96a-7789-4f20-a588-932696e1dd15" name="atEnd" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="eab89413-4d7b-4c11-be29-c59a462e17db" changeable="True" eContainingClass="c457d96a-7789-4f20-a588-932696e1dd15" name="position" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="35544c47-be01-4b8f-92c1-7290106487a1" changeable="True" eContainingClass="c457d96a-7789-4f20-a588-932696e1dd15" name="side" eType="79e44410-c5f6-4ec3-aede-71c3739325fd" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="0c9fe00a-a256-4a1a-8aa9-f4a8ea4e21df" changeable="True" eContainingClass="c457d96a-7789-4f20-a588-932696e1dd15" name="orientation" eType="c6a71fb4-389b-429d-a2c9-618df94a4314" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="ee8244e9-2c93-4766-8917-409d1a30eb34" changeable="True" eContainingClass="c457d96a-7789-4f20-a588-932696e1dd15" name="segment" eType="ca401d50-d582-4f16-9b31-d4ad2080e92f" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="0968e456-710f-443b-b5a2-5dbe89eb0fde" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Point">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="92728638-0a38-4f3b-88d6-53cca129ae57" changeable="True" eContainingClass="0968e456-710f-443b-b5a2-5dbe89eb0fde" name="inputs" eType="effb8822-c6cd-4517-9790-5a111e4e66fb" ordered="True" unique="True" upperBound="-1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="795e47e4-064c-4dbb-817c-74782e092a60" changeable="True" eContainingClass="0968e456-710f-443b-b5a2-5dbe89eb0fde" name="outputs" eType="effb8822-c6cd-4517-9790-5a111e4e66fb" ordered="True" unique="True" upperBound="-1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="eddf2e50-b8b4-4a7a-9423-9acc7b6ae9d6" changeable="True" eContainingClass="0968e456-710f-443b-b5a2-5dbe89eb0fde" name="kind" eType="be48640c-2c5b-475c-9ced-2410a03d3dcf" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="5e48c1f3-9eac-41ad-a4c6-e42674ab8c53" changeable="True" eContainingClass="0968e456-710f-443b-b5a2-5dbe89eb0fde" name="selectedInput" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="a54de579-b982-41ce-a230-1d97af09d1f2" changeable="True" eContainingClass="0968e456-710f-443b-b5a2-5dbe89eb0fde" name="selectedOutput" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="8938b4e3-57b5-42d1-bda6-a28b894b17c0" changeable="True" eContainingClass="0968e456-710f-443b-b5a2-5dbe89eb0fde" name="locked" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="8c5f79fc-cb93-404b-bc8b-7e0e52754edd" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Track">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="adc0fb64-ed3a-4867-9835-f2e01cfdc5aa" changeable="True" eContainingClass="8c5f79fc-cb93-404b-bc8b-7e0e52754edd" name="elements" eType="18de1e20-800d-4aa3-a36b-8eaed0cde3fe" ordered="True" unique="False" upperBound="-1" resolveProxies="True" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" serializable="True" name="SpeedLimit" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="7f02649c-5299-4f8e-8ab0-7ea6ddd8544e" name="Stop" eEnum="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="954bd640-90b2-4852-9e2f-f485cb6f1acc" name="Speed40" eEnum="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" value="2" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="f1b24c7a-cf41-48d3-9d00-0fca7501369f" name="Speed80" eEnum="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" value="3" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="ed3b914a-f6ac-400c-924b-dd01fe4288f6" name="Speed120" eEnum="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" value="4" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="19d22c28-bd4f-409c-bde5-6f8e585c15d3" name="Max" eEnum="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" value="5" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="be48640c-2c5b-475c-9ced-2410a03d3dcf" serializable="True" name="PointKind" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="ca1f0a87-66a4-449c-ad5f-86ab9c4fc9f7" name="FixedCrossing" eEnum="be48640c-2c5b-475c-9ced-2410a03d3dcf" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="6f8ef378-6988-4048-a7c4-6f212122dddf" name="SimplePoint" eEnum="be48640c-2c5b-475c-9ced-2410a03d3dcf" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="a66dbc54-b291-4783-a639-60c2203597bd" name="DoublePoint" eEnum="be48640c-2c5b-475c-9ced-2410a03d3dcf" value="2" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="188b20a6-312e-4acd-84f2-4002d469635b" name="SingleSlipPoint" eEnum="be48640c-2c5b-475c-9ced-2410a03d3dcf" value="3" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="9cdb5d3a-0af5-446c-b074-cbf5ec9b213f" name="DoubleSlipPoint" eEnum="be48640c-2c5b-475c-9ced-2410a03d3dcf" value="4" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="4392d532-ee04-4e82-aa35-32c979b7ac46" serializable="True" name="VertexKind" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="0cf1a9fa-fb9f-4f5c-97e2-8908e3158232" name="InnerVertex" eEnum="4392d532-ee04-4e82-aa35-32c979b7ac46" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="ba6d3e67-beb2-4781-a55d-e307f708852a" name="TrackEnd" eEnum="4392d532-ee04-4e82-aa35-32c979b7ac46" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="84d75e39-b339-4eb3-b5a5-f3e74ceb8fcf" name="StationBorder" eEnum="4392d532-ee04-4e82-aa35-32c979b7ac46" value="2" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="843e0260-620c-44e6-bf93-662c3321107c" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="NamedElement" abstract="True">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="f607e501-49b0-43d4-b85a-2fd728e9b7c1" changeable="True" eContainingClass="843e0260-620c-44e6-bf93-662c3321107c" name="name" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="c6a71fb4-389b-429d-a2c9-618df94a4314" serializable="True" name="Orientation" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="8e16effd-13df-4fcd-b52c-595c75c77464" name="Forwards" eEnum="c6a71fb4-389b-429d-a2c9-618df94a4314" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="eeb2e704-6f65-491e-a4a1-ca7f7986322a" name="Backwards" eEnum="c6a71fb4-389b-429d-a2c9-618df94a4314" value="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="79e44410-c5f6-4ec3-aede-71c3739325fd" serializable="True" name="Side" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="48e21ad6-579f-44d3-a055-948a4e9c920b" name="Both" eEnum="79e44410-c5f6-4ec3-aede-71c3739325fd" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="4a9400af-cfbc-4a03-aeb6-567e448214dc" name="Right" eEnum="79e44410-c5f6-4ec3-aede-71c3739325fd" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="9f67457d-5ed8-45a2-b88a-732a40d01f61" name="Left" eEnum="79e44410-c5f6-4ec3-aede-71c3739325fd" value="2" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="69f53be6-064f-4635-b2e5-c7fae56092d3" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="Train">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="b65b1092-9c4e-4fbf-8264-22e678fcc7ee" changeable="True" eContainingClass="69f53be6-064f-4635-b2e5-c7fae56092d3" name="length" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="cf347ede-4fef-4877-afc2-59bc90e8b97e" changeable="True" eContainingClass="69f53be6-064f-4635-b2e5-c7fae56092d3" name="speed" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="dd925ebf-1a31-475b-b3a6-52ed429dc7c9" changeable="True" eContainingClass="69f53be6-064f-4635-b2e5-c7fae56092d3" name="segments" eType="80deecc1-e036-43dc-9e33-2a9d979bda31" ordered="True" unique="True" upperBound="-1" containment="True" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="09463093-1cbd-4942-ae47-41506156001e" changeable="True" eContainingClass="69f53be6-064f-4635-b2e5-c7fae56092d3" name="position" eType="c457d96a-7789-4f20-a588-932696e1dd15" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="d250aa31-2e38-45a8-9ff2-2c459d1a19da" changeable="True" eContainingClass="69f53be6-064f-4635-b2e5-c7fae56092d3" name="acceleration" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="80deecc1-e036-43dc-9e33-2a9d979bda31" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="TrainSegment">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="eecf274b-c632-4040-94af-2fcb0e079606" changeable="True" eContainingClass="80deecc1-e036-43dc-9e33-2a9d979bda31" name="position" eType="c457d96a-7789-4f20-a588-932696e1dd15" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="b6631219-571a-4b23-901b-902eb5d588cf" changeable="True" eContainingClass="80deecc1-e036-43dc-9e33-2a9d979bda31" name="length" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="142634a8-63bf-44db-8cdf-22b14e6f2bc9" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="RouteObject" abstract="True">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="0fc9bbd7-6521-448d-9005-d1d56f36852d" defaultValueLiteral="Max" changeable="True" eContainingClass="142634a8-63bf-44db-8cdf-22b14e6f2bc9" name="speedLimit" eType="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="7beddbfa-5c69-4220-a012-2aaebdd4b48a" changeable="True" eContainingClass="142634a8-63bf-44db-8cdf-22b14e6f2bc9" name="error" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="a0364ea8-6549-45a7-af14-43d3560bd7e7" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="TrainRoute">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="c2050831-1b60-41db-a0cd-30657974457f" changeable="True" eContainingClass="a0364ea8-6549-45a7-af14-43d3560bd7e7" name="path" eType="01407e7f-f37f-48b4-93b0-54da53734495" ordered="True" unique="True" upperBound="-1" containment="True" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="546b3ef5-0a81-45af-9122-05a7c2dcd0b4" changeable="True" eContainingClass="a0364ea8-6549-45a7-af14-43d3560bd7e7" name="kind" eType="131c6c74-44fb-41dd-b4a2-fb02aeaffd2d" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="a587a695-cdbe-4729-93d5-1bddc3bcb5a3" changeable="True" eContainingClass="a0364ea8-6549-45a7-af14-43d3560bd7e7" name="startSignal" eType="f9df8a4f-68f1-4b87-90b2-dc7461e51986" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="f7f4f133-518d-4eea-aeee-fa0fed1c7d35" changeable="True" eContainingClass="a0364ea8-6549-45a7-af14-43d3560bd7e7" name="endSignal" eType="f9df8a4f-68f1-4b87-90b2-dc7461e51986" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="49ce8dd5-d885-4137-8d81-e9e13d285adf" changeable="True" eContainingClass="a0364ea8-6549-45a7-af14-43d3560bd7e7" name="protectionObjects" eType="01407e7f-f37f-48b4-93b0-54da53734495" ordered="True" unique="True" upperBound="-1" containment="True" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="ffe2b44e-cf5c-40b0-be09-380e8f17a251" changeable="True" eContainingClass="a0364ea8-6549-45a7-af14-43d3560bd7e7" name="conflictingRoutes" eType="a0364ea8-6549-45a7-af14-43d3560bd7e7" ordered="True" unique="True" upperBound="-1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="aaec2dbb-aa3d-415d-9ce8-d4159b66c3b9" changeable="True" eContainingClass="a0364ea8-6549-45a7-af14-43d3560bd7e7" name="locked" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="131c6c74-44fb-41dd-b4a2-fb02aeaffd2d" serializable="True" name="TrainRouteKind" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="86a0d828-b1ff-464c-b6ff-84a648cb8025" name="Main" eEnum="131c6c74-44fb-41dd-b4a2-fb02aeaffd2d" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="f96b5321-3e65-4900-870a-43a948d5c39f" name="Shunting" eEnum="131c6c74-44fb-41dd-b4a2-fb02aeaffd2d" value="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="01407e7f-f37f-48b4-93b0-54da53734495" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="TrainRouteObject">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="d9836aa3-2e0d-4a9e-ad3f-71af28b565ef" changeable="True" eContainingClass="01407e7f-f37f-48b4-93b0-54da53734495" name="speedLimit" eType="c98f60b3-3b2b-4478-8c4d-29c1c5f73f34" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="e5920082-a2b0-41da-81db-37336e7af69c" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="TrainRoutePoint">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="7b41d087-22cc-44ec-a946-e4063d119696" changeable="True" eContainingClass="e5920082-a2b0-41da-81db-37336e7af69c" name="originalPoint" eType="0968e456-710f-443b-b5a2-5dbe89eb0fde" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="aab9cb4e-3d9a-43de-bde6-e6fa6a3895fe" changeable="True" eContainingClass="e5920082-a2b0-41da-81db-37336e7af69c" name="selectedInput" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="dad7d5a5-f976-4c15-94e3-40e1b49e781d" changeable="True" eContainingClass="e5920082-a2b0-41da-81db-37336e7af69c" name="selectedOutput" eType="!!!REF!!!" ordered="True" unique="True" upperBound="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="a918c21c-4789-46e7-98b8-d6c4b7be7b44" ePackage="4b66ba75-8aea-4399-8b40-8e09219c9211" name="TrainRouteSegment">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="45023135-b9dc-4642-8b6c-8fe8da514617" changeable="True" eContainingClass="a918c21c-4789-46e7-98b8-d6c4b7be7b44" name="originalSegment" eType="ca401d50-d582-4f16-9b31-d4ad2080e92f" ordered="True" unique="True" upperBound="1" resolveProxies="True" />
  </eClassifiers>
</ecore:EPackage>