<?xml version="1.0" encoding="utf-8"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:type="ecore:EPackage" xmi:id="f2bdd0d4-f12a-4ba8-90d8-44827659cd6f" name="railDsl" nsURI="http://www.bme.hu/iit/vke/raildsl" nsPrefix="railDsl" xmlns:xmi="http://www.omg.org/XMI">
  <eClassifiers xmi:type="ecore:EClass" xmi:id="54f4c731-6eba-4141-bb2c-8d56b2586a89" name="Station">
    <eSuperTypes xmi:idref="71449b99-6dbb-4945-944c-c49e84ed3e53" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="1bcb1ade-0e1b-404c-a1f0-97e018f4f55c" name="declarations" eType="43cb7f15-93f9-4518-bfe5-edd12ad2278d" upperBound="-1" containment="true" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="43cb7f15-93f9-4518-bfe5-edd12ad2278d" name="Declaration" abstract="true">
    <eSuperTypes xmi:idref="71449b99-6dbb-4945-944c-c49e84ed3e53" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="bd9c9546-2724-4baf-9756-a902f39998a8" name="TrackObject" abstract="true">
    <eSuperTypes xmi:idref="43cb7f15-93f9-4518-bfe5-edd12ad2278d" />
    <eSuperTypes xmi:idref="858eb8c1-bf2b-4b3c-9728-a9300a39b1ab" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="1cc89ae9-0cbf-41c6-851b-16f807aa5262" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="f089ca4c-9a5f-40f1-ab49-14b9f38baa9c" name="Vertex">
    <eSuperTypes xmi:idref="43cb7f15-93f9-4518-bfe5-edd12ad2278d" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="6055f696-bccc-4c61-a95c-7683998314eb" name="kind" eType="abb24485-c91c-4d72-9730-435850ad21c0" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="b45bd5e8-0fef-4adc-9ae5-b8596932b65e" name="Segment">
    <eSuperTypes xmi:idref="bd9c9546-2724-4baf-9756-a902f39998a8" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="ccb27568-12c1-47e7-a135-ad71920a62cc" name="start" eType="f089ca4c-9a5f-40f1-ab49-14b9f38baa9c" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="2ea0d5e7-77c6-4a00-ab94-42c7d0233aa0" name="end" eType="f089ca4c-9a5f-40f1-ab49-14b9f38baa9c" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="89e6a536-b4a4-4348-8037-4b393ef6ab88" name="objects" eType="e72b8463-9f5b-4e52-8239-ad33f462196e" upperBound="-1" containment="true" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="e72b8463-9f5b-4e52-8239-ad33f462196e" name="SegmentObject" abstract="true">
    <eSuperTypes xmi:idref="71449b99-6dbb-4945-944c-c49e84ed3e53" />
    <eSuperTypes xmi:idref="858eb8c1-bf2b-4b3c-9728-a9300a39b1ab" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="168e8e67-bb40-4611-be12-6d919c661469" name="position" eType="a2df4ed7-47e5-45f0-b325-1475176f08cc" containment="true" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="438afcf4-cee5-4488-bdac-600ef32a853c" name="Derailer">
    <eSuperTypes xmi:idref="e72b8463-9f5b-4e52-8239-ad33f462196e" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="04947dd0-78fd-4287-a4ec-9d454dd230f8" name="active" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="d3df5ed0-3b10-4665-a27b-7985a264fa0d" name="LevelCrossing">
    <eSuperTypes xmi:idref="e72b8463-9f5b-4e52-8239-ad33f462196e" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="dce1f46a-9971-481c-b922-78c8c1e745d5" name="closed" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="41fb338e-5ac2-46d4-ba97-2a03d1704730" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="b43e1fcb-73ee-469f-9f07-3b296a021fc3" name="Signal">
    <eSuperTypes xmi:idref="e72b8463-9f5b-4e52-8239-ad33f462196e" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="6187ecf6-4b5a-4a71-8b73-b8fddf241efa" name="distantFor" eType="b43e1fcb-73ee-469f-9f07-3b296a021fc3" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="52fb28d6-3cda-4e89-aee7-47f902f5e8ed" name="main" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="990ee85f-d65d-4735-916a-88d808e9699f" name="shunting" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="4da48aa7-288a-4edd-a1a8-a73b9a5bb4bb" name="Platform">
    <eSuperTypes xmi:idref="e72b8463-9f5b-4e52-8239-ad33f462196e" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="53a4d4e7-0512-4e40-b72e-f6fbd9603d43" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="a2df4ed7-47e5-45f0-b325-1475176f08cc" name="SegmentPosition">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="2a52e6e8-b7aa-4b85-b806-d60a451a34dc" name="atStart" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="e7dabb1c-b64c-4f13-a668-c3ddc85d4b1b" name="atEnd" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="bfade506-3e91-497f-9023-d084f7f385ac" name="position" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="f6af822f-1459-4ab1-a4af-d6b55d0e6c06" name="side" eType="8f3409a3-f6d4-4826-a617-8de28540cccc" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="3db6474e-2d8d-4e46-82cf-1504e179f7af" name="orientation" eType="67b40cee-3418-4eca-b49d-15e7801ca33e" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="7b7a8c26-9b4f-469a-a126-5d4249f934c3" name="segment" eType="b45bd5e8-0fef-4adc-9ae5-b8596932b65e" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="85296c5c-9659-4f59-b895-b101ed4b9188" name="Point">
    <eSuperTypes xmi:idref="bd9c9546-2724-4baf-9756-a902f39998a8" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="988472b4-0168-497a-8a8e-0360d2a31cd2" name="inputs" eType="f089ca4c-9a5f-40f1-ab49-14b9f38baa9c" upperBound="-1" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="53ab95ba-d6f0-46d9-865b-c715ea890ba4" name="outputs" eType="f089ca4c-9a5f-40f1-ab49-14b9f38baa9c" upperBound="-1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="b7ee9463-abf3-4ac2-bc31-65541f11eea7" name="kind" eType="0f5b5560-84ed-4644-897b-d8b3292d4c01" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="6b089bdc-5701-48f1-9b65-f1d02b9dce14" name="selectedInput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="d52d37e7-6a9a-454e-9656-4e412cd81ed2" name="selectedOutput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="9018c7ee-e51d-477b-b1e5-9beade633729" name="locked" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="fcdb272f-365f-4d98-ad88-7d2752dedec0" name="Track">
    <eSuperTypes xmi:idref="43cb7f15-93f9-4518-bfe5-edd12ad2278d" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="ff1554e2-a893-4e5d-aa46-e43fac9d221e" name="elements" eType="bd9c9546-2724-4baf-9756-a902f39998a8" unique="false" upperBound="-1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="032893ab-9326-4094-bacb-5096a509e2db" name="SpeedLimit">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="eb5fa012-3374-4745-8b7a-0084e9f0da4a" name="Stop" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="21ecf042-94c1-4456-9a74-b7f19ad4f9c2" name="Speed40" value="2" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="5dbafe55-80dd-4a77-90c9-443602399a2f" name="Speed80" value="3" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="d079b4e3-0fcc-4df3-8a85-ea82379b53fb" name="Speed120" value="4" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="af9d379c-190a-40f6-9caf-27954f8c9b01" name="Max" value="5" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="0f5b5560-84ed-4644-897b-d8b3292d4c01" name="PointKind">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="af000630-26bd-4c0f-9898-b75526854762" name="FixedCrossing" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="6e7a613a-1686-4a6d-820f-bdddbe4aee6b" name="SimplePoint" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="8529e3db-52c0-46b2-9659-d871e025f4d7" name="DoublePoint" value="2" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="b3c2c557-c0a2-4807-9084-7c884e8b9202" name="SingleSlipPoint" value="3" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="65b61ed9-2430-403d-8af7-b47603dec8d1" name="DoubleSlipPoint" value="4" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="abb24485-c91c-4d72-9730-435850ad21c0" name="VertexKind">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="f5fd018e-261b-4146-893b-6fa397e5e01a" name="InnerVertex" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="f53601a1-11d7-4777-afb2-9b2255ebc1c8" name="TrackEnd" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="33fd21ec-c469-42fa-9bc7-3ca5f13ecd15" name="StationBorder" value="2" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="71449b99-6dbb-4945-944c-c49e84ed3e53" name="NamedElement" abstract="true">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="58de6ce3-19da-4892-8ca2-b5a3b3dee4df" name="name" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="67b40cee-3418-4eca-b49d-15e7801ca33e" name="Orientation">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="a6d66c2a-4aef-4606-9dac-197875b4939d" name="Forwards" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="e265f9bd-5c13-49c7-a3d2-6c515a028086" name="Backwards" value="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="8f3409a3-f6d4-4826-a617-8de28540cccc" name="Side">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="81c24cad-a8e8-4e13-9cb9-c03cd96ad517" name="Both" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="df07b547-0955-4913-921b-dd960f19b157" name="Right" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="694a735a-0258-4e98-b6e1-044630b5d4a2" name="Left" value="2" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="34340dba-3dcf-44b7-afa4-b3cb2f75e504" name="Train">
    <eSuperTypes xmi:idref="43cb7f15-93f9-4518-bfe5-edd12ad2278d" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="790cadaf-0099-4608-888b-59158bd1ddb1" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="a5e8bec1-6a6d-4034-b69e-4e371c5051fa" name="speed" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="2b86fc93-922c-4e18-bde4-e2751092ee8c" name="segments" eType="22ab250e-3b79-491c-b6e8-37dc9aa599a1" upperBound="-1" containment="true" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="af31a1ec-a57e-4579-bc44-1234ed5ea423" name="position" eType="a2df4ed7-47e5-45f0-b325-1475176f08cc" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="3605f621-7b18-4385-8cc3-6098f7a75f4a" name="acceleration" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="22ab250e-3b79-491c-b6e8-37dc9aa599a1" name="TrainSegment">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="afd13d53-80ef-4b48-beda-4dbb2d43b30b" name="position" eType="a2df4ed7-47e5-45f0-b325-1475176f08cc" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="71836c60-60e1-4ec5-b07b-b3db47678894" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="858eb8c1-bf2b-4b3c-9728-a9300a39b1ab" name="RouteObject" abstract="true">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="20d31b9d-14d9-4693-9a5e-a1853d975d9c" defaultValueLiteral="Max" name="speedLimit" eType="032893ab-9326-4094-bacb-5096a509e2db" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="9452b1b0-926c-4168-9a3a-844201ddfaa0" name="error" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="df6f7003-b861-4449-bcce-e3a5bea2c1a4" name="TrainRoute">
    <eSuperTypes xmi:idref="43cb7f15-93f9-4518-bfe5-edd12ad2278d" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="94780473-9986-4251-a1fd-249999e3b856" name="path" eType="16324a5e-3a56-432f-9aa5-3d6bbc32dbb8" upperBound="-1" containment="true" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="f65de97b-526d-4404-bb7a-998f21216282" name="kind" eType="de7efbf9-442a-4d85-bb3c-c14a725676aa" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="e456b1ce-15ea-4d6b-bb33-7aa6d7e47692" name="startSignal" eType="b43e1fcb-73ee-469f-9f07-3b296a021fc3" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="b5e246b7-71b5-421a-9176-5edc064763e2" name="endSignal" eType="b43e1fcb-73ee-469f-9f07-3b296a021fc3" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="bc11e103-ed72-4214-b85a-9fe56917fa45" name="protectionObjects" eType="16324a5e-3a56-432f-9aa5-3d6bbc32dbb8" upperBound="-1" containment="true" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="f866cb8a-7fe8-46eb-944c-5c659b0ecffb" name="conflictingRoutes" eType="df6f7003-b861-4449-bcce-e3a5bea2c1a4" upperBound="-1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="9bef1f68-ce3b-4ea6-be05-7c5c647b175e" name="locked" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="de7efbf9-442a-4d85-bb3c-c14a725676aa" name="TrainRouteKind">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="a532a44e-943d-4e06-946c-158ae6bfcc78" name="Main" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="38e32240-6355-46e5-936c-82216a36fd42" name="Shunting" value="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="16324a5e-3a56-432f-9aa5-3d6bbc32dbb8" name="TrainRouteObject">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="d24a0c10-6ba4-4c4a-b2b9-33eeec39eb95" name="speedLimit" eType="032893ab-9326-4094-bacb-5096a509e2db" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="6153c0d4-574d-47df-bf41-0f46e7e0d979" name="TrainRoutePoint">
    <eSuperTypes xmi:idref="16324a5e-3a56-432f-9aa5-3d6bbc32dbb8" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="e2769cea-c941-4749-b0ad-7168de978c27" name="originalPoint" eType="85296c5c-9659-4f59-b895-b101ed4b9188" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="176bf8f7-c641-4d0a-b2e5-d75e151cc0d0" name="selectedInput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="a90df8ca-1dd2-4f23-a221-4ea62aa918c4" name="selectedOutput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="5a3d7e69-6b1f-47fe-974e-131d3f04c922" name="TrainRouteSegment">
    <eSuperTypes xmi:idref="16324a5e-3a56-432f-9aa5-3d6bbc32dbb8" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="1b7f0bf3-8202-46dc-bde1-b9a98dfb013a" name="originalSegment" eType="b45bd5e8-0fef-4adc-9ae5-b8596932b65e" />
  </eClassifiers>
</ecore:EPackage>