<?xml version="1.0" encoding="utf-8"?>
<ecore:EPackage xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:type="ecore:EPackage" xmi:id="0f2efa00-8e17-4ff0-bab9-f9f73851009d" name="railDsl" nsURI="http://www.bme.hu/iit/vke/raildsl" nsPrefix="railDsl" xmlns:xmi="http://www.omg.org/XMI">
  <eClassifiers xmi:type="ecore:EClass" xmi:id="cfa7c5fc-29d3-485e-b410-4cd901611cc4" name="Station">
    <eSuperTypes xmi:idref="cb9d2b94-ade4-4645-9f41-704845ce846e" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="65c94af9-a7f1-4037-b403-79a5e84cf07c" name="declarations" eType="e34a32ef-4830-406a-91a0-4bfd20e477b6" upperBound="-1" containment="true" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="e34a32ef-4830-406a-91a0-4bfd20e477b6" name="Declaration" abstract="true">
    <eSuperTypes xmi:idref="cb9d2b94-ade4-4645-9f41-704845ce846e" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="7a0e2b06-05a4-4b0c-b090-3ae2d2fe7f55" name="TrackObject" abstract="true">
    <eSuperTypes xmi:idref="e34a32ef-4830-406a-91a0-4bfd20e477b6" />
    <eSuperTypes xmi:idref="e4bc8c15-f991-4b80-9ab0-ae4d4ac2f676" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="dc3fca57-ecab-4ee9-afc7-668116fcd5a4" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="63ee948e-2079-4e45-8431-c7a3cc68a8ba" name="Vertex">
    <eSuperTypes xmi:idref="e34a32ef-4830-406a-91a0-4bfd20e477b6" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="ddcbb150-cc8d-4970-bb62-df1cb40fa6cf" name="kind" eType="32233937-26ec-40c6-b0a9-7b55f9345bff" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="a3535339-dffb-460a-b89d-7af3af7fed9b" name="Segment">
    <eSuperTypes xmi:idref="7a0e2b06-05a4-4b0c-b090-3ae2d2fe7f55" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="7d8ebd93-70e1-43f4-b818-c0db360e3aa0" name="start" eType="63ee948e-2079-4e45-8431-c7a3cc68a8ba" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="bcfb72d8-a7ff-4acc-8f00-1ecbf2fb5ece" name="end" eType="63ee948e-2079-4e45-8431-c7a3cc68a8ba" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="8bf291d4-335b-4d5c-8ce9-e2f9f9043495" name="objects" eType="a3408b08-5841-4b34-bec8-c26d0ac93f99" upperBound="-1" containment="true" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="a3408b08-5841-4b34-bec8-c26d0ac93f99" name="SegmentObject" abstract="true">
    <eSuperTypes xmi:idref="cb9d2b94-ade4-4645-9f41-704845ce846e" />
    <eSuperTypes xmi:idref="e4bc8c15-f991-4b80-9ab0-ae4d4ac2f676" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="d334b4d6-127f-4586-9a0d-ac2ed76b82e3" name="position" eType="2ba77f62-393a-4f1b-9dd3-3529f5cc96b4" containment="true" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="ffb32782-013f-413f-97ab-c327d2b12e90" name="Derailer">
    <eSuperTypes xmi:idref="a3408b08-5841-4b34-bec8-c26d0ac93f99" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="ba4168d0-dfc2-40e5-9424-d1fceb5fe339" name="active" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="44ebb95b-d735-4459-9abc-af26a0ff53ce" name="LevelCrossing">
    <eSuperTypes xmi:idref="a3408b08-5841-4b34-bec8-c26d0ac93f99" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="d8e815e4-af04-422f-8b17-7c7d836929b5" name="closed" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="8094e916-5e43-4816-8ce6-87993d3cb515" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="1c3c7950-fa14-4b77-9fb7-90c9df58601e" name="Signal">
    <eSuperTypes xmi:idref="a3408b08-5841-4b34-bec8-c26d0ac93f99" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="21c573cc-d804-4269-a8ec-4dc92c43ab1a" name="distantFor" eType="1c3c7950-fa14-4b77-9fb7-90c9df58601e" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="fff801f0-f142-464e-9b87-24fa6c835b7b" name="main" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="4bf4c84d-e161-442c-b742-09d19d0a9948" name="shunting" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="8cc14973-22e0-469c-87c0-3933d1579ad8" name="Platform">
    <eSuperTypes xmi:idref="a3408b08-5841-4b34-bec8-c26d0ac93f99" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="d89321e9-8fae-4815-b8a0-fb6ab54cfd6a" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="2ba77f62-393a-4f1b-9dd3-3529f5cc96b4" name="SegmentPosition">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="cc15efba-16eb-4948-956b-b73ec77ff391" name="atStart" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="0b64f622-b341-485b-9281-4cc14cf7c1f1" name="atEnd" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="d918e2d1-3389-4b2b-8afd-cba1018bca39" name="position" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="ffd9ffa1-9365-4db9-9e46-7c99c40cb920" name="side" eType="011e89f9-0726-47f1-9d74-0d57318e86f7" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="4f4c5290-e4f0-4b55-b52e-6831c3d8a2a1" name="orientation" eType="751f0665-f142-42ce-8217-4cdd8cb33043" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="70ad7d81-7233-4119-9233-14a9519a5d47" name="segment" eType="a3535339-dffb-460a-b89d-7af3af7fed9b" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="ac9cb62d-3a50-457f-8141-f78c1aa6b70e" name="Point">
    <eSuperTypes xmi:idref="7a0e2b06-05a4-4b0c-b090-3ae2d2fe7f55" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="6f7d3902-49e2-43eb-a98f-e916ad98cd0f" name="inputs" eType="63ee948e-2079-4e45-8431-c7a3cc68a8ba" upperBound="-1" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="da8f263a-7c5f-4020-a5c4-be1f30f7e60f" name="outputs" eType="63ee948e-2079-4e45-8431-c7a3cc68a8ba" upperBound="-1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="77abf342-4fa4-4bf0-96d5-461083ce8b27" name="kind" eType="be87e1c0-9e85-48ec-afdf-2eb49812a3c3" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="c9b72436-26d3-4330-8e8c-58958c2204eb" name="selectedInput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="57e2fc4d-9abe-4472-b1a3-873064b108a9" name="selectedOutput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="e2b01288-9afd-4108-9ca6-5cdff8f2a960" name="locked" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="2fda0083-4c87-4dda-a724-b880b805381b" name="Track">
    <eSuperTypes xmi:idref="e34a32ef-4830-406a-91a0-4bfd20e477b6" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="f8c933a3-05c4-46f3-9566-cb7ada41983e" name="elements" eType="7a0e2b06-05a4-4b0c-b090-3ae2d2fe7f55" unique="false" upperBound="-1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="755ef0e2-ec5a-4bd6-bfca-c867359dd26f" name="SpeedLimit">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="ea6aeed4-5d2e-454d-9b7a-426f335be9e0" name="Stop" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="c5a4fe10-38d0-4adf-8b07-6b51b1780303" name="Speed40" value="2" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="afb5e1f9-b6c5-48ef-a36c-bb0fcbc6bdbe" name="Speed80" value="3" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="ba2a15fd-f06c-4df3-b896-de827180eb96" name="Speed120" value="4" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="c4fb7834-80ab-450b-9677-4539e99325d4" name="Max" value="5" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="be87e1c0-9e85-48ec-afdf-2eb49812a3c3" name="PointKind">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="8fdaf84e-07be-419d-ba73-57d25097dcf9" name="FixedCrossing" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="80c48f9a-1937-4fa8-9fb0-e962189b70c6" name="SimplePoint" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="274a8e60-aeec-4d67-a403-ee77bee158b6" name="DoublePoint" value="2" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="d840ea97-34d4-401d-b8ea-f63f5068868a" name="SingleSlipPoint" value="3" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="4c43d9f8-2386-4064-a372-fc1e45b3289f" name="DoubleSlipPoint" value="4" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="32233937-26ec-40c6-b0a9-7b55f9345bff" name="VertexKind">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="3b4da9d4-2352-46ac-afce-449f0ec6ff49" name="InnerVertex" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="8decc68c-c7ea-46b7-b6aa-a5802d6af341" name="TrackEnd" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="3d5f660e-bfdd-4063-83a5-3e558afec95e" name="StationBorder" value="2" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="cb9d2b94-ade4-4645-9f41-704845ce846e" name="NamedElement" abstract="true">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="a7ae7621-9e69-4f88-b17c-2ee5f0d2fa7c" name="name" eType="http://www.eclipse.org/emf/2002/Ecore#//EString" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="751f0665-f142-42ce-8217-4cdd8cb33043" name="Orientation">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="73a24d50-c6f3-412c-876d-8ac652bdc60c" name="Forwards" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="bbfbd410-aee2-46ad-8733-2693e86552a6" name="Backwards" value="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="011e89f9-0726-47f1-9d74-0d57318e86f7" name="Side">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="66191e83-234f-469b-a64d-72ee5bb81db5" name="Both" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="33b5fe06-0a02-4db6-8115-ed8cf86246b6" name="Right" value="1" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="92a9de07-b402-4094-8109-9466aa565c76" name="Left" value="2" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="cc7d65fa-a1bb-4050-8e16-17366b83355b" name="Train">
    <eSuperTypes xmi:idref="e34a32ef-4830-406a-91a0-4bfd20e477b6" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="2ff4ea86-5d1d-483b-a864-e0931f986a12" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="4de803b6-1b2b-4dbc-a223-7342d01c7e76" name="speed" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="48ee50da-7154-45f6-bf5f-9bcf0d222857" name="segments" eType="717804af-1f4b-4b31-8f34-f42ddaf03365" upperBound="-1" containment="true" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="8f94b836-19c9-4162-8ce5-b9895d631cf6" name="position" eType="2ba77f62-393a-4f1b-9dd3-3529f5cc96b4" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="0f761088-ec7e-4f5b-9616-eb512263d6d7" name="acceleration" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="717804af-1f4b-4b31-8f34-f42ddaf03365" name="TrainSegment">
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="56d706a2-9cd9-47bc-bda3-7685060f0df9" name="position" eType="2ba77f62-393a-4f1b-9dd3-3529f5cc96b4" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="bdbc4c59-901c-47af-a7a5-d8eb90a6ed13" name="length" eType="http://www.eclipse.org/emf/2002/Ecore#//EDouble" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="e4bc8c15-f991-4b80-9ab0-ae4d4ac2f676" name="RouteObject" abstract="true">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="39a2ab0a-bbdb-4c31-b40e-e32ddf27b2a1" defaultValueLiteral="Max" name="speedLimit" eType="755ef0e2-ec5a-4bd6-bfca-c867359dd26f" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="9d3b157a-9e8e-44c7-af35-fab5e83bf49c" name="error" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="a251a3f4-b59a-4c91-b4db-06add3a3137b" name="TrainRoute">
    <eSuperTypes xmi:idref="e34a32ef-4830-406a-91a0-4bfd20e477b6" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="b7ae03a7-790e-460c-b164-73993176e04f" name="path" eType="64a93e25-3eda-4d1d-b174-1de15e6cabe7" upperBound="-1" containment="true" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="279d5a5a-22f6-46f2-a39f-7be668b4379d" name="kind" eType="c2389a4f-bfd9-4ac7-8b56-1d7d26f7b8d3" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="add8cd8d-ae3b-4a41-aad3-8cc37a31999a" name="startSignal" eType="1c3c7950-fa14-4b77-9fb7-90c9df58601e" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="b6e42fe5-6764-49f7-94a0-e935e29539fd" name="endSignal" eType="1c3c7950-fa14-4b77-9fb7-90c9df58601e" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="318a4822-0db1-42ca-b569-2dcd550790ad" name="protectionObjects" eType="64a93e25-3eda-4d1d-b174-1de15e6cabe7" upperBound="-1" containment="true" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="94e46d94-2407-4820-bb83-f9193db2837c" name="conflictingRoutes" eType="a251a3f4-b59a-4c91-b4db-06add3a3137b" upperBound="-1" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="500d35e7-471a-45e8-a1bc-93a0f8c22797" name="locked" eType="http://www.eclipse.org/emf/2002/Ecore#//EBoolean" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EEnum" xmi:id="c2389a4f-bfd9-4ac7-8b56-1d7d26f7b8d3" name="TrainRouteKind">
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="ea0bc223-9cc8-4d11-80ec-4394fce39da6" name="Main" />
    <eLiterals xmi:type="ecore:EEnumLiteral" xmi:id="563ec563-53e9-4c92-a567-5d5aa597a4cf" name="Shunting" value="1" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="64a93e25-3eda-4d1d-b174-1de15e6cabe7" name="TrainRouteObject">
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="f2471670-ab1b-4f59-8815-a6f2d4036b52" name="speedLimit" eType="755ef0e2-ec5a-4bd6-bfca-c867359dd26f" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="62d9add6-e7fb-456b-a7ea-651e9309a09a" name="TrainRoutePoint">
    <eSuperTypes xmi:idref="64a93e25-3eda-4d1d-b174-1de15e6cabe7" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="b6622b98-34e9-4123-8ec2-a7e87f1e4b6b" name="originalPoint" eType="ac9cb62d-3a50-457f-8141-f78c1aa6b70e" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="567d1367-3042-48fe-89bb-2bf127284ecf" name="selectedInput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
    <eStructuralFeatures xmi:type="ecore:EAttribute" xmi:id="fe82e1f0-9805-4290-af38-f121f7bc8c35" name="selectedOutput" eType="http://www.eclipse.org/emf/2002/Ecore#//EInt" />
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" xmi:id="522b1d76-deeb-4c58-8a08-4d40b46f53ac" name="TrainRouteSegment">
    <eSuperTypes xmi:idref="64a93e25-3eda-4d1d-b174-1de15e6cabe7" />
    <eStructuralFeatures xmi:type="ecore:EReference" xmi:id="218f878a-22ed-4af3-abd1-a4afcd6f65b0" name="originalSegment" eType="a3535339-dffb-460a-b89d-7af3af7fed9b" />
  </eClassifiers>
</ecore:EPackage>