//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\sb\AppData\Local\Temp\upnawxce.5cx\SoalParser.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace MetaDslx.Soal {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ISoalParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public partial class SoalParserBaseListener : ISoalParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMain([NotNull] SoalParser.MainContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.main"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMain([NotNull] SoalParser.MainContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedName([NotNull] SoalParser.QualifiedNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.qualifiedName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedName([NotNull] SoalParser.QualifiedNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifierList([NotNull] SoalParser.IdentifierListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.identifierList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifierList([NotNull] SoalParser.IdentifierListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQualifiedNameList([NotNull] SoalParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.qualifiedNameList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQualifiedNameList([NotNull] SoalParser.QualifiedNameListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespaceDeclaration([NotNull] SoalParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.namespaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespaceDeclaration([NotNull] SoalParser.NamespaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] SoalParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] SoalParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDeclaration([NotNull] SoalParser.StructDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.structDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDeclaration([NotNull] SoalParser.StructDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.exceptionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExceptionDeclaration([NotNull] SoalParser.ExceptionDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.exceptionDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExceptionDeclaration([NotNull] SoalParser.ExceptionDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.propertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPropertyDeclaration([NotNull] SoalParser.PropertyDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.propertyDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPropertyDeclaration([NotNull] SoalParser.PropertyDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaceDeclaration([NotNull] SoalParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.interfaceDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaceDeclaration([NotNull] SoalParser.InterfaceDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.operationDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperationDeclaration([NotNull] SoalParser.OperationDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.operationDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperationDeclaration([NotNull] SoalParser.OperationDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameterList([NotNull] SoalParser.ParameterListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.parameterList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameterList([NotNull] SoalParser.ParameterListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter([NotNull] SoalParser.ParameterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.parameter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter([NotNull] SoalParser.ParameterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.bindingDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindingDeclaration([NotNull] SoalParser.BindingDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.bindingDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindingDeclaration([NotNull] SoalParser.BindingDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.bindingLayers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBindingLayers([NotNull] SoalParser.BindingLayersContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.bindingLayers"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBindingLayers([NotNull] SoalParser.BindingLayersContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.transportLayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransportLayer([NotNull] SoalParser.TransportLayerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.transportLayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransportLayer([NotNull] SoalParser.TransportLayerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.transportLayerKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTransportLayerKind([NotNull] SoalParser.TransportLayerKindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.transportLayerKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTransportLayerKind([NotNull] SoalParser.TransportLayerKindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.encodingLayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncodingLayer([NotNull] SoalParser.EncodingLayerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.encodingLayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncodingLayer([NotNull] SoalParser.EncodingLayerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.encodingLayerKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEncodingLayerKind([NotNull] SoalParser.EncodingLayerKindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.encodingLayerKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEncodingLayerKind([NotNull] SoalParser.EncodingLayerKindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.protocolLayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocolLayer([NotNull] SoalParser.ProtocolLayerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.protocolLayer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocolLayer([NotNull] SoalParser.ProtocolLayerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.protocolLayerKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProtocolLayerKind([NotNull] SoalParser.ProtocolLayerKindContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.protocolLayerKind"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProtocolLayerKind([NotNull] SoalParser.ProtocolLayerKindContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.endpointDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndpointDeclaration([NotNull] SoalParser.EndpointDeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.endpointDeclaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndpointDeclaration([NotNull] SoalParser.EndpointDeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.endpointProperties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndpointProperties([NotNull] SoalParser.EndpointPropertiesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.endpointProperties"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndpointProperties([NotNull] SoalParser.EndpointPropertiesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.endpointProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndpointProperty([NotNull] SoalParser.EndpointPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.endpointProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndpointProperty([NotNull] SoalParser.EndpointPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.endpointBindingProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndpointBindingProperty([NotNull] SoalParser.EndpointBindingPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.endpointBindingProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndpointBindingProperty([NotNull] SoalParser.EndpointBindingPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.endpointAddressProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndpointAddressProperty([NotNull] SoalParser.EndpointAddressPropertyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.endpointAddressProperty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndpointAddressProperty([NotNull] SoalParser.EndpointAddressPropertyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnType([NotNull] SoalParser.ReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnType([NotNull] SoalParser.ReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTypeReference([NotNull] SoalParser.TypeReferenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.typeReference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTypeReference([NotNull] SoalParser.TypeReferenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSimpleType([NotNull] SoalParser.SimpleTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.simpleType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSimpleType([NotNull] SoalParser.SimpleTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.objectType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectType([NotNull] SoalParser.ObjectTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.objectType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectType([NotNull] SoalParser.ObjectTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimitiveType([NotNull] SoalParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.primitiveType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimitiveType([NotNull] SoalParser.PrimitiveTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.voidType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVoidType([NotNull] SoalParser.VoidTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.voidType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVoidType([NotNull] SoalParser.VoidTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.onewayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOnewayType([NotNull] SoalParser.OnewayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.onewayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOnewayType([NotNull] SoalParser.OnewayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.nullableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullableType([NotNull] SoalParser.NullableTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.nullableType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullableType([NotNull] SoalParser.NullableTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayType([NotNull] SoalParser.ArrayTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.arrayType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayType([NotNull] SoalParser.ArrayTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdentifier([NotNull] SoalParser.IdentifierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.identifier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdentifier([NotNull] SoalParser.IdentifierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteral([NotNull] SoalParser.LiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteral([NotNull] SoalParser.LiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.nullLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullLiteral([NotNull] SoalParser.NullLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.nullLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullLiteral([NotNull] SoalParser.NullLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBooleanLiteral([NotNull] SoalParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.booleanLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBooleanLiteral([NotNull] SoalParser.BooleanLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntegerLiteral([NotNull] SoalParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.integerLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntegerLiteral([NotNull] SoalParser.IntegerLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.decimalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecimalLiteral([NotNull] SoalParser.DecimalLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.decimalLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecimalLiteral([NotNull] SoalParser.DecimalLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.scientificLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScientificLiteral([NotNull] SoalParser.ScientificLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.scientificLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScientificLiteral([NotNull] SoalParser.ScientificLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="SoalParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringLiteral([NotNull] SoalParser.StringLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="SoalParser.stringLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringLiteral([NotNull] SoalParser.StringLiteralContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace MetaDslx.Soal
