//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\balaz\AppData\Local\Temp\l3mhdzl2.agz\SoalParser.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MetaDslx.Languages.Soal {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="SoalParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface ISoalParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.main"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMain([NotNull] SoalParser.MainContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] SoalParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] SoalParser.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifier([NotNull] SoalParser.QualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.identifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifierList([NotNull] SoalParser.IdentifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.qualifierList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifierList([NotNull] SoalParser.QualifierListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.annotationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationList([NotNull] SoalParser.AnnotationListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.returnAnnotationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnAnnotationList([NotNull] SoalParser.ReturnAnnotationListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] SoalParser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.returnAnnotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnAnnotation([NotNull] SoalParser.ReturnAnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.annotationHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationHead([NotNull] SoalParser.AnnotationHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.annotationBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationBody([NotNull] SoalParser.AnnotationBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.annotationPropertyList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationPropertyList([NotNull] SoalParser.AnnotationPropertyListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.annotationProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationProperty([NotNull] SoalParser.AnnotationPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.annotationPropertyValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationPropertyValue([NotNull] SoalParser.AnnotationPropertyValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.namespaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceDeclaration([NotNull] SoalParser.NamespaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.namespaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNamespaceBody([NotNull] SoalParser.NamespaceBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] SoalParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.enumDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumDeclaration([NotNull] SoalParser.EnumDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.enumBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumBody([NotNull] SoalParser.EnumBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.enumLiterals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLiterals([NotNull] SoalParser.EnumLiteralsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.enumLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnumLiteral([NotNull] SoalParser.EnumLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaration([NotNull] SoalParser.StructDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructBody([NotNull] SoalParser.StructBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.propertyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertyDeclaration([NotNull] SoalParser.PropertyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.databaseDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatabaseDeclaration([NotNull] SoalParser.DatabaseDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.databaseBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatabaseBody([NotNull] SoalParser.DatabaseBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.entityReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntityReference([NotNull] SoalParser.EntityReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.interfaceDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceDeclaration([NotNull] SoalParser.InterfaceDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.interfaceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaceBody([NotNull] SoalParser.InterfaceBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.operationDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationDeclaration([NotNull] SoalParser.OperationDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.operationHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationHead([NotNull] SoalParser.OperationHeadContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.parameterList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameterList([NotNull] SoalParser.ParameterListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter([NotNull] SoalParser.ParameterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.operationResult"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationResult([NotNull] SoalParser.OperationResultContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentDeclaration([NotNull] SoalParser.ComponentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentBody([NotNull] SoalParser.ComponentBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentElements([NotNull] SoalParser.ComponentElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentElement([NotNull] SoalParser.ComponentElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentService"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentService([NotNull] SoalParser.ComponentServiceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentReference([NotNull] SoalParser.ComponentReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>componentServiceOrReferenceEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.componentServiceOrReferenceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentServiceOrReferenceEmptyBody([NotNull] SoalParser.ComponentServiceOrReferenceEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>componentServiceOrReferenceNonEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.componentServiceOrReferenceBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentServiceOrReferenceNonEmptyBody([NotNull] SoalParser.ComponentServiceOrReferenceNonEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentServiceOrReferenceElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentServiceOrReferenceElement([NotNull] SoalParser.ComponentServiceOrReferenceElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentProperty([NotNull] SoalParser.ComponentPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentImplementation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentImplementation([NotNull] SoalParser.ComponentImplementationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.componentLanguage"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComponentLanguage([NotNull] SoalParser.ComponentLanguageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.compositeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeDeclaration([NotNull] SoalParser.CompositeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.compositeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeBody([NotNull] SoalParser.CompositeBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.assemblyDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblyDeclaration([NotNull] SoalParser.AssemblyDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.compositeElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeElements([NotNull] SoalParser.CompositeElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.compositeElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeElement([NotNull] SoalParser.CompositeElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.compositeComponent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeComponent([NotNull] SoalParser.CompositeComponentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.compositeWire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompositeWire([NotNull] SoalParser.CompositeWireContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.wireSource"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWireSource([NotNull] SoalParser.WireSourceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.wireTarget"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWireTarget([NotNull] SoalParser.WireTargetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.deploymentDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeploymentDeclaration([NotNull] SoalParser.DeploymentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.deploymentBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeploymentBody([NotNull] SoalParser.DeploymentBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.deploymentElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeploymentElements([NotNull] SoalParser.DeploymentElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.deploymentElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeploymentElement([NotNull] SoalParser.DeploymentElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.environmentDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnvironmentDeclaration([NotNull] SoalParser.EnvironmentDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.environmentBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEnvironmentBody([NotNull] SoalParser.EnvironmentBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.runtimeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuntimeDeclaration([NotNull] SoalParser.RuntimeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.runtimeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuntimeReference([NotNull] SoalParser.RuntimeReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.assemblyReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssemblyReference([NotNull] SoalParser.AssemblyReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.databaseReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDatabaseReference([NotNull] SoalParser.DatabaseReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.bindingDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindingDeclaration([NotNull] SoalParser.BindingDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.bindingBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindingBody([NotNull] SoalParser.BindingBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.bindingLayers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBindingLayers([NotNull] SoalParser.BindingLayersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.transportLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTransportLayer([NotNull] SoalParser.TransportLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.httpTransportLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHttpTransportLayer([NotNull] SoalParser.HttpTransportLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>httpTransportLayerEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.httpTransportLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHttpTransportLayerEmptyBody([NotNull] SoalParser.HttpTransportLayerEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>httpTransportLayerNonEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.httpTransportLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHttpTransportLayerNonEmptyBody([NotNull] SoalParser.HttpTransportLayerNonEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.restTransportLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRestTransportLayer([NotNull] SoalParser.RestTransportLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>restTransportLayerEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.restTransportLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRestTransportLayerEmptyBody([NotNull] SoalParser.RestTransportLayerEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>restTransportLayerNonEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.restTransportLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRestTransportLayerNonEmptyBody([NotNull] SoalParser.RestTransportLayerNonEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.webSocketTransportLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWebSocketTransportLayer([NotNull] SoalParser.WebSocketTransportLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>webSocketTransportLayerEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.webSocketTransportLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWebSocketTransportLayerEmptyBody([NotNull] SoalParser.WebSocketTransportLayerEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>webSocketTransportLayerNonEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.webSocketTransportLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWebSocketTransportLayerNonEmptyBody([NotNull] SoalParser.WebSocketTransportLayerNonEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.httpTransportLayerProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHttpTransportLayerProperties([NotNull] SoalParser.HttpTransportLayerPropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.httpSslProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHttpSslProperty([NotNull] SoalParser.HttpSslPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.httpClientAuthenticationProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHttpClientAuthenticationProperty([NotNull] SoalParser.HttpClientAuthenticationPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.encodingLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEncodingLayer([NotNull] SoalParser.EncodingLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.soapEncodingLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoapEncodingLayer([NotNull] SoalParser.SoapEncodingLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>soapEncodingLayerEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.soapEncodingLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoapEncodingLayerEmptyBody([NotNull] SoalParser.SoapEncodingLayerEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>soapEncodingLayerNonEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.soapEncodingLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoapEncodingLayerNonEmptyBody([NotNull] SoalParser.SoapEncodingLayerNonEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.xmlEncodingLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlEncodingLayer([NotNull] SoalParser.XmlEncodingLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>xmlEncodingLayerEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.xmlEncodingLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlEncodingLayerEmptyBody([NotNull] SoalParser.XmlEncodingLayerEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>xmlEncodingLayerNonEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.xmlEncodingLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitXmlEncodingLayerNonEmptyBody([NotNull] SoalParser.XmlEncodingLayerNonEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.jsonEncodingLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonEncodingLayer([NotNull] SoalParser.JsonEncodingLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>jsonEncodingLayerEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.jsonEncodingLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonEncodingLayerEmptyBody([NotNull] SoalParser.JsonEncodingLayerEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>jsonEncodingLayerNonEmptyBody</c>
	/// labeled alternative in <see cref="SoalParser.jsonEncodingLayerBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonEncodingLayerNonEmptyBody([NotNull] SoalParser.JsonEncodingLayerNonEmptyBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.soapEncodingProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoapEncodingProperties([NotNull] SoalParser.SoapEncodingPropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.soapVersionProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoapVersionProperty([NotNull] SoalParser.SoapVersionPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.soapMtomProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoapMtomProperty([NotNull] SoalParser.SoapMtomPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.soapStyleProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSoapStyleProperty([NotNull] SoalParser.SoapStylePropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.protocolLayer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocolLayer([NotNull] SoalParser.ProtocolLayerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.protocolLayerKind"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProtocolLayerKind([NotNull] SoalParser.ProtocolLayerKindContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.endpointDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndpointDeclaration([NotNull] SoalParser.EndpointDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.endpointBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndpointBody([NotNull] SoalParser.EndpointBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.endpointProperties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndpointProperties([NotNull] SoalParser.EndpointPropertiesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.endpointProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndpointProperty([NotNull] SoalParser.EndpointPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.endpointBindingProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndpointBindingProperty([NotNull] SoalParser.EndpointBindingPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.endpointAddressProperty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndpointAddressProperty([NotNull] SoalParser.EndpointAddressPropertyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] SoalParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.typeReference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeReference([NotNull] SoalParser.TypeReferenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.simpleType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleType([NotNull] SoalParser.SimpleTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.nulledType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNulledType([NotNull] SoalParser.NulledTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.referenceType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReferenceType([NotNull] SoalParser.ReferenceTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.objectType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectType([NotNull] SoalParser.ObjectTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.valueType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValueType([NotNull] SoalParser.ValueTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.voidType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVoidType([NotNull] SoalParser.VoidTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.onewayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOnewayType([NotNull] SoalParser.OnewayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.operationReturnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperationReturnType([NotNull] SoalParser.OperationReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.nullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullableType([NotNull] SoalParser.NullableTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.nonNullableType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonNullableType([NotNull] SoalParser.NonNullableTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.nonNullableArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNonNullableArrayType([NotNull] SoalParser.NonNullableArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.arrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayType([NotNull] SoalParser.ArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.simpleArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimpleArrayType([NotNull] SoalParser.SimpleArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.nulledArrayType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNulledArrayType([NotNull] SoalParser.NulledArrayTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.constantValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantValue([NotNull] SoalParser.ConstantValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.typeofValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeofValue([NotNull] SoalParser.TypeofValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] SoalParser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.identifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifiers([NotNull] SoalParser.IdentifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] SoalParser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullLiteral([NotNull] SoalParser.NullLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] SoalParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.integerLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntegerLiteral([NotNull] SoalParser.IntegerLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.decimalLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecimalLiteral([NotNull] SoalParser.DecimalLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.scientificLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScientificLiteral([NotNull] SoalParser.ScientificLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] SoalParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="SoalParser.contextualKeywords"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContextualKeywords([NotNull] SoalParser.ContextualKeywordsContext context);
}
} // namespace MetaDslx.Languages.Soal
