//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\balaz\AppData\Local\Temp\ehmgu4np.5v4\AnnotatedAntlr4Parser.g4 by ANTLR 4.5.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace MetaDslx.Compiler {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="AnnotatedAntlr4Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.1")]
[System.CLSCompliant(false)]
public interface IAnnotatedAntlr4ParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.grammarSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrammarSpec([NotNull] AnnotatedAntlr4Parser.GrammarSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.grammarType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGrammarType([NotNull] AnnotatedAntlr4Parser.GrammarTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.prequelConstruct"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrequelConstruct([NotNull] AnnotatedAntlr4Parser.PrequelConstructContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.optionsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionsSpec([NotNull] AnnotatedAntlr4Parser.OptionsSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.option"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOption([NotNull] AnnotatedAntlr4Parser.OptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.optionValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOptionValue([NotNull] AnnotatedAntlr4Parser.OptionValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.delegateGrammars"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelegateGrammars([NotNull] AnnotatedAntlr4Parser.DelegateGrammarsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.delegateGrammar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDelegateGrammar([NotNull] AnnotatedAntlr4Parser.DelegateGrammarContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.tokensSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTokensSpec([NotNull] AnnotatedAntlr4Parser.TokensSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.annotatedId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotatedId([NotNull] AnnotatedAntlr4Parser.AnnotatedIdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAction([NotNull] AnnotatedAntlr4Parser.ActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.actionScopeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActionScopeName([NotNull] AnnotatedAntlr4Parser.ActionScopeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.modeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModeSpec([NotNull] AnnotatedAntlr4Parser.ModeSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.rules"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRules([NotNull] AnnotatedAntlr4Parser.RulesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleSpec([NotNull] AnnotatedAntlr4Parser.RuleSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.parserRuleSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParserRuleSpec([NotNull] AnnotatedAntlr4Parser.ParserRuleSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.exceptionGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionGroup([NotNull] AnnotatedAntlr4Parser.ExceptionGroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.exceptionHandler"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExceptionHandler([NotNull] AnnotatedAntlr4Parser.ExceptionHandlerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.finallyClause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFinallyClause([NotNull] AnnotatedAntlr4Parser.FinallyClauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.rulePrequel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRulePrequel([NotNull] AnnotatedAntlr4Parser.RulePrequelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleReturns"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleReturns([NotNull] AnnotatedAntlr4Parser.RuleReturnsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.throwsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitThrowsSpec([NotNull] AnnotatedAntlr4Parser.ThrowsSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.localsSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalsSpec([NotNull] AnnotatedAntlr4Parser.LocalsSpecContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleAction([NotNull] AnnotatedAntlr4Parser.RuleActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleModifiers"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleModifiers([NotNull] AnnotatedAntlr4Parser.RuleModifiersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleModifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleModifier([NotNull] AnnotatedAntlr4Parser.RuleModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleBlock([NotNull] AnnotatedAntlr4Parser.RuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleAltList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleAltList([NotNull] AnnotatedAntlr4Parser.RuleAltListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.labeledAlt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledAlt([NotNull] AnnotatedAntlr4Parser.LabeledAltContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.propertiesBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPropertiesBlock([NotNull] AnnotatedAntlr4Parser.PropertiesBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerRule"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerRule([NotNull] AnnotatedAntlr4Parser.LexerRuleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerRuleBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerRuleBlock([NotNull] AnnotatedAntlr4Parser.LexerRuleBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerAltList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerAltList([NotNull] AnnotatedAntlr4Parser.LexerAltListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerAlt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerAlt([NotNull] AnnotatedAntlr4Parser.LexerAltContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerElements"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerElements([NotNull] AnnotatedAntlr4Parser.LexerElementsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerElement([NotNull] AnnotatedAntlr4Parser.LexerElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.labeledLexerElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledLexerElement([NotNull] AnnotatedAntlr4Parser.LabeledLexerElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerBlock([NotNull] AnnotatedAntlr4Parser.LexerBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerCommands"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerCommands([NotNull] AnnotatedAntlr4Parser.LexerCommandsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerCommand([NotNull] AnnotatedAntlr4Parser.LexerCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerCommandName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerCommandName([NotNull] AnnotatedAntlr4Parser.LexerCommandNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerCommandExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerCommandExpr([NotNull] AnnotatedAntlr4Parser.LexerCommandExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.altList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAltList([NotNull] AnnotatedAntlr4Parser.AltListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlternative([NotNull] AnnotatedAntlr4Parser.AlternativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] AnnotatedAntlr4Parser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.labeledElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLabeledElement([NotNull] AnnotatedAntlr4Parser.LabeledElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ebnf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEbnf([NotNull] AnnotatedAntlr4Parser.EbnfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.blockSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockSuffix([NotNull] AnnotatedAntlr4Parser.BlockSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ebnfSuffix"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEbnfSuffix([NotNull] AnnotatedAntlr4Parser.EbnfSuffixContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.lexerAtom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLexerAtom([NotNull] AnnotatedAntlr4Parser.LexerAtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.atom"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtom([NotNull] AnnotatedAntlr4Parser.AtomContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.notSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotSet([NotNull] AnnotatedAntlr4Parser.NotSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.blockSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockSet([NotNull] AnnotatedAntlr4Parser.BlockSetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.setElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSetElement([NotNull] AnnotatedAntlr4Parser.SetElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] AnnotatedAntlr4Parser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.ruleref"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRuleref([NotNull] AnnotatedAntlr4Parser.RulerefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] AnnotatedAntlr4Parser.RangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminal([NotNull] AnnotatedAntlr4Parser.TerminalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.elementOptions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementOptions([NotNull] AnnotatedAntlr4Parser.ElementOptionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.elementOption"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElementOption([NotNull] AnnotatedAntlr4Parser.ElementOptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] AnnotatedAntlr4Parser.IdContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.annotation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotation([NotNull] AnnotatedAntlr4Parser.AnnotationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.annotationBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationBody([NotNull] AnnotatedAntlr4Parser.AnnotationBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.annotationAttributeList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationAttributeList([NotNull] AnnotatedAntlr4Parser.AnnotationAttributeListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.annotationAttribute"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAnnotationAttribute([NotNull] AnnotatedAntlr4Parser.AnnotationAttributeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.expressionList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpressionList([NotNull] AnnotatedAntlr4Parser.ExpressionListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.qualifiedName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitQualifiedName([NotNull] AnnotatedAntlr4Parser.QualifiedNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] AnnotatedAntlr4Parser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral([NotNull] AnnotatedAntlr4Parser.LiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier([NotNull] AnnotatedAntlr4Parser.IdentifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.boolLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLiteral([NotNull] AnnotatedAntlr4Parser.BoolLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="AnnotatedAntlr4Parser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullLiteral([NotNull] AnnotatedAntlr4Parser.NullLiteralContext context);
}
} // namespace MetaDslx.Compiler
